### PR TITLE
Demo Version

### PR DESCRIPTION
**Pull request by daniel-j-henderson**
I don't know what the things are that make it not automatically merge, but it looks right to me. @busunkim96 you should give it a try, we don't have to merge it in tonight but maybe you can do another video that demos the host part (Press play, skip, pause, add a song). In both the SpotifyActivity and QueueActivity we just use the first playlist that is returned for the user, so they should both be the same playlists. I think I also assume people already have a playlist created. For some reason I haven't gotten the refresh to work on the QueueActivity, and the player is a little buggy still.

Also, do y'all want to meet at like 10-1030 tomorrow morning at the physics building? We can go over parts and such? @cosh9041 @busunkim96 @luwo1701

### CODE REVIEW

**Comment by busunkim96** [comment]
I'm good to meet at 10 in Duane. The merge looks like it'll be messy, so I'll just pull from your branch to do the video for tomorrow. @daniel-j-henderson @luwo1701 @cosh9041

**Comment by daniel-j-henderson** [comment]
Cool Let me know if there's any trouble, I'll be up for a while

**Comment by busunkim96** [comment]
@daniel-j-henderson So what exactly do I need to do to add a song to the queue? I'm on SpotifyActivity and adding a song but nothing seems to happen. 

Is there some dummy user with songs already in the backend that I need to login as?

**Comment by daniel-j-henderson** [comment]
Go ahead and log in as mytest@gmail.com Mytest and you can add songs to the queue in the SpotifyActivity. There's already like 10 songs in there. It'll work as any user who already has an existing playlist. Also be aware that the songs are in no particular order.

**Comment by busunkim96** [comment]
@daniel-j-henderson  Cool, that seems to be working. How do I get a song to start playing?

EDIT: Never mind, it looks like it's working when I do it in the emulator.

**Comment by daniel-j-henderson** [comment]
Does pressing the play button not work? I guess you'd also need to log in to spotify... My account is user: djhqazwsx pass: daniel The skip forward button should also work more or less.

**Comment by cosh9041** [comment]
I'm good to meet today, can do anytime between now and the start of our class

**Comment by luwo1701** [comment]
Yea we should meet up I'm good for 10 at the physics lab

**Pull request merged**
